-- Reordena as colunas do IPTU
SELECT
	"NUMERO DO CONTRIBUINTE" as "SQL",
	"SQLC",
	"SQLCond",
	"NUMERO DO CONDOMINIO",
	"ANO DO EXERCICIO",
	"CEP DO IMOVEL",
	"CODLOG DO IMOVEL",
	"NOME DE LOGRADOURO DO IMOVEL",
	"NUMERO DO IMOVEL",
	"COMPLEMENTO DO IMOVEL",
	"BAIRRO DO IMOVEL",
	"REFERENCIA DO IMOVEL",
	"ANO DA CONSTRUCAO CORRIGIDO",
	"QUANTIDADE DE PAVIMENTOS",
	"AREA DO TERRENO",
	"AREA OCUPADA",
	"FRACAO IDEAL",
	"AREA CONSTRUIDA",
	"QUANTIDADE DE ESQUINAS/FRENTES",
	"TIPO DE TERRENO",
	"TESTADA PARA CALCULO",
	"TIPO DE USO DO IMOVEL",
	"TIPO DE PADRAO DA CONSTRUCAO",
	"FATOR DE OBSOLESCENCIA",
	"VALOR DO M2 DO TERRENO",
	"VALOR DO M2 DE CONSTRUCAO",
	"TIPO DE CONTRIBUINTE 1",
	"CPF/CNPJ DO CONTRIBUINTE 1",
	"NOME DO CONTRIBUINTE 1",
	"TIPO DE CONTRIBUINTE 2",
	"CPF/CNPJ DO CONTRIBUINTE 2",
	"NOME DO CONTRIBUINTE 2",
	"ANO DE INICIO DA VIDA DO CONTRIBUINTE",
	"MES DE INICIO DA VIDA DO CONTRIBUINTE",
	"FASE DO CONTRIBUINTE"
INTO iptu."TEMP_2019"
FROM iptu._2019;

-- Remove a tabela antiga e renomeia a tabela temporária
DROP TABLE iptu._2019;
ALTER TABLE iptu."TEMP_2019" RENAME TO iptu._2019;